<a href="https://colab.research.google.com/github/Gabrielcs96/Estudos-iniciais-em-Python/blob/main/1%C2%B0_C%C3%B3digo_de_Python_estudando_estat%C3%ADstica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Primeiro código em Python
Aqui eu fiz um código super extenso, testando a biblioteca Pandas e usando o "google.colab" para importar arquivos para dentro do Colab.

O Maior foco que eu tive aqui foi a criação de dataframes e o tratamento dos números, assim eu consegui entender bsaicamente como a biblioteca funciona e como eu faço operações com os dataframes.

Além disso eu usei também a Numpy para operar vetores e matrizes, entendendo como a biblioteca funciona e me tornando capaz de utilizar ela em situações reais;

por fim eu fiz algumas operações com números, como a linguagem é dinamicamente é tipada eu tentei algumas coisas para saber o que funciona e o que não aqui.

#Iniciando com o carregamento, tratamento e utilização de datasets

In [ ]:
 from google.colab import files
 from google.colab import drive
 import pandas as pd

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/PYTHON - E.B.A /Cópia de top10s.csv", encoding = "ISO-8859-1")

FileNotFoundError: ignored

In [ ]:
df.head()

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,80,217,19,4,83
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,64,263,24,23,82
2,3,TiK ToK,Kesha,dance pop,2010,120,84,76,-3,29,71,200,10,14,80
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,71,295,0,4,79
4,5,Just the Way You Are,Bruno Mars,pop,2010,109,84,64,-5,9,43,221,2,4,78

In [ ]:
files.upload()

In [ ]:
dfs = pd.read_csv('SpotifyTopSongsByCountry - May 2020.csv')

In [ ]:
dfs.head()

,Country,Continent,Rank,Title,Artists,Album,Explicit,Duration
0,Global,Global,1,Rain On Me (with Ariana Grande),"Lady Gaga, Ariana Grande",Rain On Me (with Ariana Grande),0,3:02
1,Global,Global,2,Blinding Lights,The Weeknd,After Hours,0,3:20
2,Global,Global,3,ROCKSTAR (feat. Roddy Ricch),"DaBaby, Roddy Ricch",BLAME IT ON BABY,1,3:01
3,Global,Global,4,Roses - Imanbek Remix,"SAINt JHN, Imanbek",Roses (Imanbek Remix),1,2:56
4,Global,Global,5,Toosie Slide,Drake,Dark Lane Demo Tapes,1,4:07

#Entendendo as colunas do dataset:
Genre - the genre of the track

Year - the release year of the recording. Note that due to vagaries of releases, re-releases, re-issues and general madness, sometimes the release years are not what you'd expect.

Added - the earliest date you added the track to your collection.

Beats Per Minute (BPM) - The tempo of the song.

Energy - The energy of a song - the higher the value, the more energtic. song

Danceability - The higher the value, the easier it is to dance to this song.

Loudness (dB) - The higher the value, the louder the song.

Liveness - The higher the value, the more likely the song is a live recording.

Valence - The higher the value, the more positive mood for the song.


Length - The duration of the song.

Acousticness - The higher the value the more acoustic the song is.

Speechiness - The higher the value the more spoken word the song contains.

Popularity - The higher the value the more popular the song is.

Duration - The length of the song.

In [ ]:
df.tail()
#Mostrar as últimas linhas

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
598,599,Find U Again (feat. Camila Cabello),Mark Ronson,dance pop,2019,104,66,61,-7,20,16,176,1,3,75
599,600,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,2019,95,79,75,-6,7,61,206,21,12,75
600,601,"No Brainer (feat. Justin Bieber, Chance the Ra...",DJ Khaled,dance pop,2019,136,76,53,-5,9,65,260,7,34,70
601,602,Nothing Breaks Like a Heart (feat. Miley Cyrus),Mark Ronson,dance pop,2019,114,79,60,-6,42,24,217,1,7,69
602,603,Kills You Slowly,The Chainsmokers,electropop,2019,150,44,70,-9,13,23,213,6,6,67

In [ ]:
df.info()
#Trazer informações do dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 603 entries, 0 to 602
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  603 non-null    int64
 1   title       603 non-null    object
 2   artist      603 non-null    object
 3   top genre   603 non-null    object
 4   year        603 non-null    int64
 5   bpm         603 non-null    int64
 6   nrgy        603 non-null    int64
 7   dnce        603 non-null    int64
 8   dB          603 non-null    int64
 9   live        603 non-null    int64
 10  val         603 non-null    int64
 11  dur         603 non-null    int64
 12  acous       603 non-null    int64
 13  spch        603 non-null    int64
 14  pop         603 non-null    int64
dtypes: int64(12), object(3)
memory usage: 70.8+ KB

In [ ]:
df.dtypes

Unnamed: 0     int64
title         object
artist        object
top genre     object
year           int64
bpm            int64
nrgy           int64
dnce           int64
dB             int64
live           int64
val            int64
dur            int64
acous          int64
spch           int64
pop            int64
dtype: object

In [ ]:
df.select_dtypes(include='int64')

     Unnamed: 0  year  bpm  nrgy  dnce  dB  live  val  dur  acous  spch  pop
0             1  2010   97    89    67  -4     8   80  217     19     4   83
1             2  2010   87    93    75  -5    52   64  263     24    23   82
2             3  2010  120    84    76  -3    29   71  200     10    14   80
3             4  2010  119    92    70  -4     8   71  295      0     4   79
4             5  2010  109    84    64  -5     9   43  221      2     4   78
..          ...   ...  ...   ...   ...  ..   ...  ...  ...    ...   ...  ...
598         599  2019  104    66    61  -7    20   16  176      1     3   75
599         600  2019   95    79    75  -6     7   61  206     21    12   75
600         601  2019  136    76    53  -5     9   65  260      7    34   70
601         602  2019  114    79    60  -6    42   24  217      1     7   69
602         603  2019  150    44    70  -9    13   23  213      6     6   67

[603 rows x 12 columns]

In [ ]:
df.select_dtypes(include='object')

,title,artist,top genre
0,"Hey, Soul Sister",Train,neo mellow
1,Love The Way You Lie,Eminem,detroit hip hop
2,TiK ToK,Kesha,dance pop
3,Bad Romance,Lady Gaga,dance pop
4,Just the Way You Are,Bruno Mars,pop
...,...,...,...
598,Find U Again (feat. Camila Cabello),Mark Ronson,dance pop
599,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop
600,"No Brainer (feat. Justin Bieber, Chance the Ra...",DJ Khaled,dance pop
601,Nothing Breaks Like a Heart (feat. Miley Cyrus),Mark Ronson,dance pop
602,Kills You Slowly,The Chainsmokers,electropop

In [ ]:
df.describe()

,Unnamed: 0,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
count,603.000000,603.000000,603.000000,603.000000,603.000000,603.000000,603.000000,603.000000,603.000000,603.000000,603.000000,603.000000
mean,302.000000,2014.592040,118.545605,70.504146,64.379768,-5.578773,17.774461,52.225539,224.674959,14.326700,8.358209,66.520730
std,174.215384,2.607057,24.795358,16.310664,13.378718,2.798020,13.102543,22.513020,34.130059,20.766165,7.483162,14.517746
min,1.000000,2010.000000,0.000000,0.000000,0.000000,-60.000000,0.000000,0.000000,134.000000,0.000000,0.000000,0.000000
25%,151.500000,2013.000000,100.000000,61.000000,57.000000,-6.000000,9.000000,35.000000,202.000000,2.000000,4.000000,60.000000
50%,302.000000,2015.000000,120.000000,74.000000,66.000000,-5.000000,12.000000,52.000000,221.000000,6.000000,5.000000,69.000000
75%,452.500000,2017.000000,129.000000,82.000000,73.000000,-4.000000,24.000000,69.000000,239.500000,17.000000,9.000000,76.000000
max,603.000000,2019.000000,206.000000,98.000000,97.000000,-2.000000,74.000000,98.000000,424.000000,99.000000,48.000000,99.000000

In [ ]:
df.isna().sum()
#Saber quantas casas são nulas dentro do Data Frame

Unnamed: 0    0
title         0
artist        0
top genre     0
year          0
bpm           0
nrgy          0
dnce          0
dB            0
live          0
val           0
dur           0
acous         0
spch          0
pop           0
dtype: int64

In [ ]:
df['title']
#VBai mostra apenas as os títulos, ou seja... o noem dos títulos das músicas, porque eu selecionei o " null"

0                                       Hey, Soul Sister
1                                   Love The Way You Lie
2                                                TiK ToK
3                                            Bad Romance
4                                   Just the Way You Are
                             ...
598                  Find U Again (feat. Camila Cabello)
599        Cross Me (feat. Chance the Rapper & PnB Rock)
600    No Brainer (feat. Justin Bieber, Chance the Ra...
601      Nothing Breaks Like a Heart (feat. Miley Cyrus)
602                                     Kills You Slowly
Name: title, Length: 603, dtype: object

In [ ]:
df['artist'].unique()
#trazer as questões sem repetições por conta do "unique"

array(['Train', 'Eminem', 'Kesha', 'Lady Gaga', 'Bruno Mars',
       'Justin Bieber', 'Taio Cruz', 'OneRepublic', 'Alicia Keys',
       'Rihanna', 'Flo Rida', 'Mike Posner', 'Far East Movement', 'Usher',
       'Sean Kingston', 'The Black Eyed Peas', 'Adam Lambert', 'Maroon 5',
       'Neon Trees', 'Selena Gomez & The Scene', 'Enrique Iglesias',
       'Katy Perry', 'Britney Spears', '3OH!3', 'David Guetta',
       'Christina Aguilera', 'Florence + The Machine', 'Shakira',
       'Tinie Tempah', 'T.I.', 'Martin Solveig', 'Christina Perri',
       'Adele', 'Pitbull', 'Beyoncé', 'Hot Chelle Rae', 'Avril Lavigne',
       'Kanye West', 'LMFAO', 'Jessie J', 'Jennifer Lopez', 'Chris Brown',
       'Sleeping At Last', 'Nicki Minaj', 'P!nk', 'Coldplay',
       'One Direction', 'Taylor Swift', 'Carly Rae Jepsen',
       'Kelly Clarkson', 'Owl City', 'The Wanted', 'fun.',
       'Ellie Goulding', 'Gym Class Heroes', 'Avicii', 'The Script',
       'Miley Cyrus', 'Swedish House Mafia', 'Daft Punk', 'James Arthur',
       'Robin Thicke', 'Demi Lovato', 'Zedd', 'Lana Del Rey',
       'Calvin Harris', 'Drake', 'Sara Bareilles',
       'Macklemore & Ryan Lewis', 'Labrinth', 'Ne-Yo', 'Ariana Grande',
       'Justin Timberlake', 'will.i.am', 'Icona Pop', 'Fergie',
       'Little Mix', 'Emeli Sandé', 'Selena Gomez', 'Austin Mahone',
       'Jonas Brothers', 'Mariah Carey', 'Ciara', 'Jewel',
       'Kelly Rowland', 'John Legend', 'Sam Smith', 'Pharrell Williams',
       'MAGIC!', 'Passenger', 'Bastille', 'Lorde', 'John Newman',
       'Disclosure', 'Michael Jackson', '5 Seconds of Summer',
       'Iggy Azalea', 'Jason Derulo', 'The Chainsmokers', 'Birdy',
       'A Great Big World', 'Sia', 'Charli XCX', 'Lily Allen',
       'Lea Michele', 'Ed Sheeran', 'The Weeknd', 'Mark Ronson', 'Hozier',
       'Shawn Mendes', 'Mr. Probz', 'Zara Larsson', 'Fifth Harmony',
       'Clean Bandit', 'Meghan Trainor', 'Nick Jonas', 'Paloma Faith',
       'Olly Murs', 'Naughty Boy', 'Alessia Cara', 'Sigala', 'Rudimental',
       'Lost Frequencies', 'Robin Schulz', 'Lilly Wood and The Prick',
       'Wiz Khalifa', 'Alesso', 'Madonna', 'Gwen Stefani', 'Jess Glynne',
       'Hilary Duff', 'Ricky Martin', 'Jennifer Hudson', 'DNCE',
       'Martin Garrix', 'Lukas Graham', 'G-Eazy', 'Hailee Steinfeld',
       'BØRNS', 'Major Lazer', 'MØ', 'Tove Lo', 'ZAYN', 'Bebe Rexha',
       'Snakehips', 'Missy Elliott', 'Years & Years', 'Charlie Puth',
       'Janet Jackson', 'Joey Montana', 'Nelly Furtado', 'DJ Snake',
       'Kygo', 'DJ Khaled', 'Luis Fonsi', 'Camila Cabello', 'Jonas Blue',
       'CNCO', 'Cardi B', 'Alan Walker', 'Liam Payne', 'Niall Horan',
       'Cashmere Cat', 'Galantis', 'Dua Lipa', 'Silk City', 'Marshmello',
       'Halsey', 'Troye Sivan', 'Dan + Shay', 'Rita Ora', 'Harry Styles',
       'Ansel Elgort', 'J Balvin', 'N.E.R.D', 'Hayley Kiyoko', 'RedOne',
       'Lewis Capaldi', 'SHAED', 'Lizzo', 'Mabel', 'Khalid', 'R3HAB',
       'Daddy Yankee'], dtype=object)

In [ ]:
df['artist'].nunique()
# Contar a quantidade de " artistas diferentes" que tem na playlist

184

In [ ]:
df.shape
#mostrar a quantidade de linhas por colunas

(603, 15)

In [ ]:
df.size
#Mostrar a quantidade de "quadradinhos" ( células) totais.

9045

In [ ]:
df.columns
#Traz todas as colunas

Index(['Unnamed: 0', 'title', 'artist', 'top genre', 'year', 'bpm', 'nrgy',
       'dnce', 'dB', 'live', 'val', 'dur', 'acous', 'spch', 'pop'],
      dtype='object')

In [ ]:
df.memory_usage()
#Descobrir o tamanho que cada coisinha está tomando na tabela

Index          128
Unnamed: 0    4824
title         4824
artist        4824
top genre     4824
year          4824
bpm           4824
nrgy          4824
dnce          4824
dB            4824
live          4824
val           4824
dur           4824
acous         4824
spch          4824
pop           4824
dtype: int64

In [ ]:
df.nsmallest(5,'nrgy')

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
442,443,Million Years Ago,Adele,british soul,2016,0,0,0,-60,0,0,227,0,0,0
431,432,Start,John Legend,neo mellow,2016,110,4,52,-15,9,26,310,99,4,47
255,256,Not About Angels,Birdy,neo mellow,2014,116,14,41,-10,9,23,190,97,4,56
249,250,Say Something,A Great Big World,neo mellow,2014,138,15,45,-9,9,9,229,87,3,61
436,437,Beautiful Birds (feat. Birdy),Passenger,folk-pop,2016,86,17,39,-13,11,14,214,91,3,36

In [ ]:
df.nlargest(5,'nrgy')

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
50,51,Hello,Martin Solveig,big room,2010,128,98,67,-3,10,45,191,1,3,0
198,199,Pom Poms,Jonas Brothers,boy band,2013,148,98,68,-2,28,90,198,7,9,52
134,135,Don't Stop the Party (feat. TJR),Pitbull,dance pop,2012,127,96,72,-4,38,95,206,1,9,59
181,182,Rock N Roll,Avril Lavigne,canadian pop,2013,184,96,47,-3,34,67,207,1,13,61
24,25,All The Right Moves,OneRepublic,dance pop,2010,146,95,53,-4,28,65,238,26,5,65

In [ ]:
df_ops=df.drop_duplicates(subset='title', keep='last')
#copiando os dados de "df" para o " Df_ops" e excluindo duplicadas do "title" onde eu mantenho apenas o que chegou " por último"

In [ ]:
display(df_ops)

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,80,217,19,4,83
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,64,263,24,23,82
2,3,TiK ToK,Kesha,dance pop,2010,120,84,76,-3,29,71,200,10,14,80
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,71,295,0,4,79
5,6,Baby,Justin Bieber,canadian pop,2010,65,86,73,-5,11,54,214,4,14,77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
598,599,Find U Again (feat. Camila Cabello),Mark Ronson,dance pop,2019,104,66,61,-7,20,16,176,1,3,75
599,600,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,2019,95,79,75,-6,7,61,206,21,12,75
600,601,"No Brainer (feat. Justin Bieber, Chance the Ra...",DJ Khaled,dance pop,2019,136,76,53,-5,9,65,260,7,34,70
601,602,Nothing Breaks Like a Heart (feat. Miley Cyrus),Mark Ronson,dance pop,2019,114,79,60,-6,42,24,217,1,7,69
602,603,Kills You Slowly,The Chainsmokers,electropop,2019,150,44,70,-9,13,23,213,6,6,67

In [ ]:
df_ops

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,80,217,19,4,83
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,64,263,24,23,82
2,3,TiK ToK,Kesha,dance pop,2010,120,84,76,-3,29,71,200,10,14,80
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,71,295,0,4,79
5,6,Baby,Justin Bieber,canadian pop,2010,65,86,73,-5,11,54,214,4,14,77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
598,599,Find U Again (feat. Camila Cabello),Mark Ronson,dance pop,2019,104,66,61,-7,20,16,176,1,3,75
599,600,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,2019,95,79,75,-6,7,61,206,21,12,75
600,601,"No Brainer (feat. Justin Bieber, Chance the Ra...",DJ Khaled,dance pop,2019,136,76,53,-5,9,65,260,7,34,70
601,602,Nothing Breaks Like a Heart (feat. Miley Cyrus),Mark Ronson,dance pop,2019,114,79,60,-6,42,24,217,1,7,69
602,603,Kills You Slowly,The Chainsmokers,electropop,2019,150,44,70,-9,13,23,213,6,6,67

In [ ]:
df_ops.fillna(0)
# preenchendo todos os campos nulos como " 0"

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,80,217,19,4,83
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,64,263,24,23,82
2,3,TiK ToK,Kesha,dance pop,2010,120,84,76,-3,29,71,200,10,14,80
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,71,295,0,4,79
5,6,Baby,Justin Bieber,canadian pop,2010,65,86,73,-5,11,54,214,4,14,77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
598,599,Find U Again (feat. Camila Cabello),Mark Ronson,dance pop,2019,104,66,61,-7,20,16,176,1,3,75
599,600,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,2019,95,79,75,-6,7,61,206,21,12,75
600,601,"No Brainer (feat. Justin Bieber, Chance the Ra...",DJ Khaled,dance pop,2019,136,76,53,-5,9,65,260,7,34,70
601,602,Nothing Breaks Like a Heart (feat. Miley Cyrus),Mark Ronson,dance pop,2019,114,79,60,-6,42,24,217,1,7,69
602,603,Kills You Slowly,The Chainsmokers,electropop,2019,150,44,70,-9,13,23,213,6,6,67

In [ ]:
df_ops.T
#Transpondo todos os campos nulos

,0,1,2,3,5,6,7,8,9,10,...,593,594,595,596,597,598,599,600,601,602
Unnamed: 0,1,2,3,4,6,7,8,9,10,11,...,594,595,596,597,598,599,600,601,602,603
title,"Hey, Soul Sister",Love The Way You Lie,TiK ToK,Bad Romance,Baby,Dynamite,Secrets,Empire State of Mind (Part II) Broken Down,Only Girl (In The World),Club Can't Handle Me (feat. David Guetta),...,Call You Mine,No Guidance (feat. Drake),Antisocial (with Travis Scott),"Taki Taki (feat. Selena Gomez, Ozuna & Cardi B)",Con Calma - Remix,Find U Again (feat. Camila Cabello),Cross Me (feat. Chance the Rapper & PnB Rock),"No Brainer (feat. Justin Bieber, Chance the Ra...",Nothing Breaks Like a Heart (feat. Miley Cyrus),Kills You Slowly
artist,Train,Eminem,Kesha,Lady Gaga,Justin Bieber,Taio Cruz,OneRepublic,Alicia Keys,Rihanna,Flo Rida,...,The Chainsmokers,Chris Brown,Ed Sheeran,DJ Snake,Daddy Yankee,Mark Ronson,Ed Sheeran,DJ Khaled,Mark Ronson,The Chainsmokers
top genre,neo mellow,detroit hip hop,dance pop,dance pop,canadian pop,dance pop,dance pop,hip pop,barbadian pop,dance pop,...,electropop,dance pop,pop,electronic trap,latin,dance pop,pop,dance pop,dance pop,electropop
year,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,...,2019,2019,2019,2019,2019,2019,2019,2019,2019,2019
bpm,97,87,120,119,65,120,148,93,126,128,...,104,93,152,96,94,104,95,136,114,150
nrgy,89,93,84,92,86,78,76,37,72,87,...,70,45,82,80,87,66,79,76,79,44
dnce,67,75,76,70,73,75,52,48,79,62,...,59,70,72,84,74,61,75,53,60,70
dB,-4,-5,-3,-4,-5,-4,-6,-8,-4,-4,...,-6,-7,-5,-4,-3,-7,-6,-5,-6,-9
live,8,52,29,8,11,4,12,12,7,6,...,34,16,36,6,4,20,7,9,42,13
val,80,64,71,71,54,82,38,14,61,47,...,52,14,91,62,61,16,61,65,24,23
dur,217,263,200,295,214,203,225,216,235,235,...,218,261,162,213,181,176,206,260,217,213
acous,19,24,10,0,4,0,7,74,13,3,...,20,12,13,16,17,1,21,7,1,6
spch,4,23,14,4,14,9,4,3,4,3,...,3,15,5,23,5,3,12,34,7,6
pop,83,82,80,79,77,77,77,76,73,73,...,81,81,78,77,76,75,75,70,69,67

In [ ]:
df_ops.sample(10)
#pegar 10 carinhas aletórios para testar a amostra

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
345,346,Bloodstream,Ed Sheeran,pop,2015,89,59,48,-6,6,27,309,20,5,52
268,269,Thinking out Loud,Ed Sheeran,pop,2015,79,45,78,-6,18,59,282,47,3,84
60,61,Tonight Tonight,Hot Chelle Rae,dance pop,2011,100,78,69,-5,16,81,200,8,12,75
490,491,Younger Now,Miley Cyrus,dance pop,2017,122,87,55,-5,14,33,249,0,6,62
168,169,Let Me Love You (Until You Learn To Love Yours...,Ne-Yo,dance pop,2013,125,68,66,-7,37,25,252,25,4,70
579,580,Happier,Marshmello,brostep,2019,100,79,69,-3,17,67,214,19,5,90
433,434,Higher,Carly Rae Jepsen,canadian pop,2016,114,87,65,-5,37,44,234,1,6,46
102,103,Firework,Katy Perry,dance pop,2011,124,83,64,-5,11,65,228,14,5,25
554,555,What I Need (feat. Kehlani),Hayley Kiyoko,dance pop,2018,104,79,63,-4,16,41,220,5,6,67
239,240,A Little Party Never Killed Nobody (All We Got),Fergie,dance pop,2014,130,62,76,-6,9,52,241,1,18,65

#ENCONTRANDO VALORES ESPECÍFICOS NO DATAFRAME

In [ ]:
df.query("artist== 'Ariana Grande'")
# Ao usar o " .query e atribuir dentro da função o campo e o que se está sendo procurado, você consegue achar o resultado da sua pesqusa, como num " filtro " do Excel!

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
171,172,The Way,Ariana Grande,dance pop,2013,82,88,65,-3,8,86,227,29,11,68
221,222,Problem,Ariana Grande,dance pop,2014,103,81,66,-5,16,63,194,2,15,75
287,288,Love Me Harder,Ariana Grande,dance pop,2015,99,71,47,-4,8,24,236,1,3,76
291,292,Break Free,Ariana Grande,dance pop,2015,130,70,69,-5,20,28,215,1,5,75
323,324,Focus,Ariana Grande,dance pop,2015,100,88,67,-6,44,79,211,27,24,66
368,369,Into You,Ariana Grande,dance pop,2016,108,73,62,-6,14,37,244,2,11,80
381,382,Dangerous Woman,Ariana Grande,dance pop,2016,134,60,66,-5,36,29,236,5,4,78
451,452,Side To Side,Ariana Grande,dance pop,2017,159,74,65,-6,24,61,226,5,23,80
513,514,no tears left to cry,Ariana Grande,dance pop,2018,122,71,70,-6,29,35,206,4,6,84

In [ ]:
df.query("artist== 'Katy Perry'")

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
28,29,Teenage Dream,Katy Perry,dance pop,2010,120,80,72,-5,13,59,228,2,4,63
29,30,California Gurls,Katy Perry,dance pop,2010,125,75,79,-4,18,40,235,0,5,62
77,78,E.T.,Katy Perry,dance pop,2011,152,87,62,-5,37,76,230,2,18,66
101,102,Last Friday Night (T.G.I.F.),Katy Perry,dance pop,2011,126,81,65,-4,67,72,231,0,4,27
102,103,Firework,Katy Perry,dance pop,2011,124,83,64,-5,11,65,228,14,5,25
124,125,Part Of Me,Katy Perry,dance pop,2012,130,92,68,-5,7,77,216,0,4,71
127,128,Wide Awake,Katy Perry,dance pop,2012,160,68,51,-5,39,57,221,7,4,68
128,129,The One That Got Away,Katy Perry,dance pop,2012,134,80,69,-4,16,88,227,0,4,67
144,145,Roar,Katy Perry,dance pop,2013,180,77,55,-5,35,46,224,0,4,78
216,217,Dark Horse,Katy Perry,dance pop,2014,132,59,65,-6,17,35,216,0,5,78
237,238,This Is How We Do,Katy Perry,dance pop,2014,96,64,69,-6,15,80,204,2,5,66
242,243,Birthday,Katy Perry,dance pop,2014,126,67,72,-5,11,84,215,9,7,65
357,358,Legendary Lovers,Katy Perry,dance pop,2015,126,84,62,-5,8,39,224,2,8,41
408,409,Rise,Katy Perry,dance pop,2016,101,64,55,-6,11,44,203,5,5,66
468,469,Swish Swish,Katy Perry,dance pop,2017,120,71,84,-5,10,57,243,2,4,73
469,470,Chained To The Rhythm,Katy Perry,dance pop,2017,190,80,45,-5,20,47,238,8,17,72
485,486,Bon appétit,Katy Perry,dance pop,2017,106,79,80,-6,22,52,228,13,6,68

In [ ]:
df.query('dur>200')

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,80,217,19,4,83
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,64,263,24,23,82
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,71,295,0,4,79
4,5,Just the Way You Are,Bruno Mars,pop,2010,109,84,64,-5,9,43,221,2,4,78
5,6,Baby,Justin Bieber,canadian pop,2010,65,86,73,-5,11,54,214,4,14,77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
596,597,"Taki Taki (feat. Selena Gomez, Ozuna & Cardi B)",DJ Snake,electronic trap,2019,96,80,84,-4,6,62,213,16,23,77
599,600,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,2019,95,79,75,-6,7,61,206,21,12,75
600,601,"No Brainer (feat. Justin Bieber, Chance the Ra...",DJ Khaled,dance pop,2019,136,76,53,-5,9,65,260,7,34,70
601,602,Nothing Breaks Like a Heart (feat. Miley Cyrus),Mark Ronson,dance pop,2019,114,79,60,-6,42,24,217,1,7,69
602,603,Kills You Slowly,The Chainsmokers,electropop,2019,150,44,70,-9,13,23,213,6,6,67

In [ ]:
df.loc[df['artist'] == 'Ariana Grande']
#Tô executando a mesma coisa que eu fiz em cima, porém aqui usando a função " LOC"

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
171,172,The Way,Ariana Grande,dance pop,2013,82,88,65,-3,8,86,227,29,11,68
221,222,Problem,Ariana Grande,dance pop,2014,103,81,66,-5,16,63,194,2,15,75
287,288,Love Me Harder,Ariana Grande,dance pop,2015,99,71,47,-4,8,24,236,1,3,76
291,292,Break Free,Ariana Grande,dance pop,2015,130,70,69,-5,20,28,215,1,5,75
323,324,Focus,Ariana Grande,dance pop,2015,100,88,67,-6,44,79,211,27,24,66
368,369,Into You,Ariana Grande,dance pop,2016,108,73,62,-6,14,37,244,2,11,80
381,382,Dangerous Woman,Ariana Grande,dance pop,2016,134,60,66,-5,36,29,236,5,4,78
451,452,Side To Side,Ariana Grande,dance pop,2017,159,74,65,-6,24,61,226,5,23,80
513,514,no tears left to cry,Ariana Grande,dance pop,2018,122,71,70,-6,29,35,206,4,6,84

In [ ]:
df.isin(['Ariana Grande','Katy Perry'])

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
598,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
599,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
600,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
601,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
602,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
(df['artist'] == 'Queen').any()
# Nessa função aqui, eu tô questionando se a banda Queen está inserida em alguma parte do Data Frame

False

#OPERAÇÕES COM DATAFRAMES

In [ ]:
df_ops.head()
# mostrando o dataframe de novo

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,80,217,19,4,83
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,64,263,24,23,82
2,3,TiK ToK,Kesha,dance pop,2010,120,84,76,-3,29,71,200,10,14,80
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,71,295,0,4,79
5,6,Baby,Justin Bieber,canadian pop,2010,65,86,73,-5,11,54,214,4,14,77

In [ ]:
df_ops.drop(columns=['spch'], inplace=True)
# Dropei o " spch" da tabela/dataframe

<ipython-input-40-15891da2f0e1>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ops.drop(columns=['spch'], inplace=True)

In [ ]:
df_ops['dur'].mean()
#Trouxe a média matemática ( aritimética ) do " dur"

224.63698630136986

In [ ]:
df_ops['dur'].min()
#Trouxe o mínimo do Dur

134

In [ ]:
df_ops['dur'].max()
#Máximo do Dur

424

In [ ]:
df.agg({'acous':'mean','dur':'max'})
#trpuxe aqui a média do "acous" e a duração máxima , só que ao mesmo tempo

acous     14.3267
dur      424.0000
dtype: float64

In [ ]:
df_ops['dur'].cumsum()
#contando de forma incremental o "dur"

0         217
1         480
2         680
3         975
5        1189
        ...
598    130292
599    130498
600    130758
601    130975
602    131188
Name: dur, Length: 584, dtype: int64

In [ ]:
df_ops.sort_values(by='dur', ascending = False)
# Ordenei pelo "duração", neste caso, concendi ao ascending o " false", ou seja, ele vai trazer do maior para o menor

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,pop
188,189,TKO,Justin Timberlake,dance pop,2013,138,68,61,-7,43,49,424,1,58
422,423,Wish That You Were Here - From Miss Peregrine...,Florence + The Machine,art pop,2016,94,57,37,-6,13,12,403,72,57
63,64,Monster,Kanye West,chicago rap,2011,125,69,63,-6,67,10,379,0,73
162,163,Lose Yourself to Dance,Daft Punk,electro,2013,100,66,83,-8,8,67,354,8,72
194,195,Take Back the Night,Justin Timberlake,dance pop,2013,107,66,59,-5,64,33,353,4,54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581,582,Good as Hell (feat. Ariana Grande) - Remix,Lizzo,escape room,2019,96,89,67,-3,74,48,159,30,90
492,493,Reality (feat. Janieck Devy) - Radio Edit,Lost Frequencies,belgian edm,2017,122,64,73,-7,8,53,158,2,59
174,175,I Love It (feat. Charli XCX),Icona Pop,candy pop,2013,126,91,71,-3,15,82,157,1,67
591,592,All Around The World (La La La),R3HAB,big room,2019,125,86,73,-5,11,52,148,48,82
330,331,Mark My Words,Justin Bieber,canadian pop,2015,114,26,38,-9,17,52,134,88,63

In [ ]:
df_ops.sort_values(by='dur', ascending = True)
# Fiz o mesmo de cima, só que ao contrário. Aqui tô trazendo do menor para o maior mesmo !

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,pop
330,331,Mark My Words,Justin Bieber,canadian pop,2015,114,26,38,-9,17,52,134,88,63
591,592,All Around The World (La La La),R3HAB,big room,2019,125,86,73,-5,11,52,148,48,82
174,175,I Love It (feat. Charli XCX),Icona Pop,candy pop,2013,126,91,71,-3,15,82,157,1,67
492,493,Reality (feat. Janieck Devy) - Radio Edit,Lost Frequencies,belgian edm,2017,122,64,73,-7,8,53,158,2,59
334,335,Reality - Radio Edit,Lost Frequencies,belgian edm,2015,122,70,71,-8,7,60,159,2,61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,195,Take Back the Night,Justin Timberlake,dance pop,2013,107,66,59,-5,64,33,353,4,54
162,163,Lose Yourself to Dance,Daft Punk,electro,2013,100,66,83,-8,8,67,354,8,72
63,64,Monster,Kanye West,chicago rap,2011,125,69,63,-6,67,10,379,0,73
422,423,Wish That You Were Here - From Miss Peregrine...,Florence + The Machine,art pop,2016,94,57,37,-6,13,12,403,72,57
188,189,TKO,Justin Timberlake,dance pop,2013,138,68,61,-7,43,49,424,1,58

In [ ]:
df_ops['year'].astype(str)
# Converti o campo " ano " para string

0      2010
1      2010
2      2010
3      2010
5      2010
       ...
598    2019
599    2019
600    2019
601    2019
602    2019
Name: year, Length: 584, dtype: object

In [ ]:
df_ops['year'].cumsum()

0         2010
1         4020
2         6030
3         8040
5        10050
        ...
598    1168469
599    1170488
600    1172507
601    1174526
602    1176545
Name: year, Length: 584, dtype: int64

In [ ]:
pd.get_dummies(df_ops,columns=['artist'])
#Criei uma variável numa coluna para confirmar se a " música" pertence ao " artista"

,Unnamed: 0,title,top genre,year,bpm,nrgy,dnce,dB,live,val,...,artist_Train,artist_Troye Sivan,artist_Usher,artist_Wiz Khalifa,artist_Years & Years,artist_ZAYN,artist_Zara Larsson,artist_Zedd,artist_fun.,artist_will.i.am
0,1,"Hey, Soul Sister",neo mellow,2010,97,89,67,-4,8,80,...,1,0,0,0,0,0,0,0,0,0
1,2,Love The Way You Lie,detroit hip hop,2010,87,93,75,-5,52,64,...,0,0,0,0,0,0,0,0,0,0
2,3,TiK ToK,dance pop,2010,120,84,76,-3,29,71,...,0,0,0,0,0,0,0,0,0,0
3,4,Bad Romance,dance pop,2010,119,92,70,-4,8,71,...,0,0,0,0,0,0,0,0,0,0
5,6,Baby,canadian pop,2010,65,86,73,-5,11,54,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
598,599,Find U Again (feat. Camila Cabello),dance pop,2019,104,66,61,-7,20,16,...,0,0,0,0,0,0,0,0,0,0
599,600,Cross Me (feat. Chance the Rapper & PnB Rock),pop,2019,95,79,75,-6,7,61,...,0,0,0,0,0,0,0,0,0,0
600,601,"No Brainer (feat. Justin Bieber, Chance the Ra...",dance pop,2019,136,76,53,-5,9,65,...,0,0,0,0,0,0,0,0,0,0
601,602,Nothing Breaks Like a Heart (feat. Miley Cyrus),dance pop,2019,114,79,60,-6,42,24,...,0,0,0,0,0,0,0,0,0,0
602,603,Kills You Slowly,electropop,2019,150,44,70,-9,13,23,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df_ops.assign(energy_dance= lambda df: df['dnce']*df['nrgy'])
#usei o assign para criar um novo campo onde, eu multiplico o dnce pelo nrgy

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,pop,energy_dance
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,80,217,19,83,5963
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,64,263,24,82,6975
2,3,TiK ToK,Kesha,dance pop,2010,120,84,76,-3,29,71,200,10,80,6384
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,71,295,0,79,6440
5,6,Baby,Justin Bieber,canadian pop,2010,65,86,73,-5,11,54,214,4,77,6278
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
598,599,Find U Again (feat. Camila Cabello),Mark Ronson,dance pop,2019,104,66,61,-7,20,16,176,1,75,4026
599,600,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,2019,95,79,75,-6,7,61,206,21,75,5925
600,601,"No Brainer (feat. Justin Bieber, Chance the Ra...",DJ Khaled,dance pop,2019,136,76,53,-5,9,65,260,7,70,4028
601,602,Nothing Breaks Like a Heart (feat. Miley Cyrus),Mark Ronson,dance pop,2019,114,79,60,-6,42,24,217,1,69,4740
602,603,Kills You Slowly,The Chainsmokers,electropop,2019,150,44,70,-9,13,23,213,6,67,3080

#GROUP BY  DFs
Ou seja...  fundindo os dfs !

In [ ]:
df_ops.T

,0,1,2,3,5,6,7,8,9,10,...,593,594,595,596,597,598,599,600,601,602
Unnamed: 0,1,2,3,4,6,7,8,9,10,11,...,594,595,596,597,598,599,600,601,602,603
title,"Hey, Soul Sister",Love The Way You Lie,TiK ToK,Bad Romance,Baby,Dynamite,Secrets,Empire State of Mind (Part II) Broken Down,Only Girl (In The World),Club Can't Handle Me (feat. David Guetta),...,Call You Mine,No Guidance (feat. Drake),Antisocial (with Travis Scott),"Taki Taki (feat. Selena Gomez, Ozuna & Cardi B)",Con Calma - Remix,Find U Again (feat. Camila Cabello),Cross Me (feat. Chance the Rapper & PnB Rock),"No Brainer (feat. Justin Bieber, Chance the Ra...",Nothing Breaks Like a Heart (feat. Miley Cyrus),Kills You Slowly
artist,Train,Eminem,Kesha,Lady Gaga,Justin Bieber,Taio Cruz,OneRepublic,Alicia Keys,Rihanna,Flo Rida,...,The Chainsmokers,Chris Brown,Ed Sheeran,DJ Snake,Daddy Yankee,Mark Ronson,Ed Sheeran,DJ Khaled,Mark Ronson,The Chainsmokers
top genre,neo mellow,detroit hip hop,dance pop,dance pop,canadian pop,dance pop,dance pop,hip pop,barbadian pop,dance pop,...,electropop,dance pop,pop,electronic trap,latin,dance pop,pop,dance pop,dance pop,electropop
year,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,...,2019,2019,2019,2019,2019,2019,2019,2019,2019,2019
bpm,97,87,120,119,65,120,148,93,126,128,...,104,93,152,96,94,104,95,136,114,150
nrgy,89,93,84,92,86,78,76,37,72,87,...,70,45,82,80,87,66,79,76,79,44
dnce,67,75,76,70,73,75,52,48,79,62,...,59,70,72,84,74,61,75,53,60,70
dB,-4,-5,-3,-4,-5,-4,-6,-8,-4,-4,...,-6,-7,-5,-4,-3,-7,-6,-5,-6,-9
live,8,52,29,8,11,4,12,12,7,6,...,34,16,36,6,4,20,7,9,42,13
val,80,64,71,71,54,82,38,14,61,47,...,52,14,91,62,61,16,61,65,24,23
dur,217,263,200,295,214,203,225,216,235,235,...,218,261,162,213,181,176,206,260,217,213
acous,19,24,10,0,4,0,7,74,13,3,...,20,12,13,16,17,1,21,7,1,6
pop,83,82,80,79,77,77,77,76,73,73,...,81,81,78,77,76,75,75,70,69,67

In [ ]:
df_ops.head()

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,pop
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,80,217,19,83
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,64,263,24,82
2,3,TiK ToK,Kesha,dance pop,2010,120,84,76,-3,29,71,200,10,80
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,71,295,0,79
5,6,Baby,Justin Bieber,canadian pop,2010,65,86,73,-5,11,54,214,4,77

In [ ]:
df.groupby('artist').count()

,Unnamed: 0,title,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
artist,,,,,,,,,,,,,,
3OH!3,1,1,1,1,1,1,1,1,1,1,1,1,1,1
5 Seconds of Summer,1,1,1,1,1,1,1,1,1,1,1,1,1,1
A Great Big World,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Adam Lambert,2,2,2,2,2,2,2,2,2,2,2,2,2,2
Adele,10,10,10,10,10,10,10,10,10,10,10,10,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZAYN,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Zara Larsson,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Zedd,6,6,6,6,6,6,6,6,6,6,6,6,6,6
fun.,2,2,2,2,2,2,2,2,2,2,2,2,2,2
will.i.am,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [ ]:
df.groupby('artist')['title'].count()

artist
3OH!3                   1
5 Seconds of Summer     1
A Great Big World       1
Adam Lambert            2
Adele                  10
                       ..
ZAYN                    5
Zara Larsson            1
Zedd                    6
fun.                    2
will.i.am               1
Name: title, Length: 184, dtype: int64

In [ ]:
df.groupby(['artist','year'])['title'].count()

artist               year
3OH!3                2010    1
5 Seconds of Summer  2014    1
A Great Big World    2014    1
Adam Lambert         2010    2
Adele                2011    2
                            ..
Zedd                 2015    1
                     2016    1
                     2017    2
fun.                 2012    2
will.i.am            2013    1
Name: title, Length: 409, dtype: int64

In [ ]:
df.groupby(['artist','year']).agg({'year':'count','dur':'mean'})

                          year    dur
artist              year
3OH!3               2010     1  192.0
5 Seconds of Summer 2014     1  202.0
A Great Big World   2014     1  229.0
Adam Lambert        2010     2  227.5
Adele               2011     2  256.5
...                        ...    ...
Zedd                2015     1  240.0
                    2016     1  225.0
                    2017     2  207.5
fun.                2012     2  264.0
will.i.am           2013     1  280.0

[409 rows x 2 columns]

In [ ]:
df_groupedyear= df.groupby('year')

In [ ]:
df_groupedyear.ngroups

10

In [ ]:
df_groupedyear.groups

{2010: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50], 2011: [51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103], 2012: [104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138], 2013: [139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209], 2014: [210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267], 2015: [268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362], 2016: [363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442], 2017: [443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507], 2018: [508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571], 2019: [572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602]}

In [ ]:
df_groupedyear.size()

year
2010    51
2011    53
2012    35
2013    71
2014    58
2015    95
2016    80
2017    65
2018    64
2019    31
dtype: int64

In [ ]:
df_groupedyear.get_group(2014)

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
210,211,All of Me,John Legend,neo mellow,2014,120,26,42,-7,13,33,270,92,3,86
211,212,Stay With Me,Sam Smith,pop,2014,84,42,42,-6,11,18,173,59,4,85
212,213,Summer,Calvin Harris,dance pop,2014,128,86,60,-4,14,74,223,2,3,80
213,214,"Happy - From ""Despicable Me 2""",Pharrell Williams,dance pop,2014,160,82,65,-5,9,96,233,22,18,79
214,215,Rude,MAGIC!,pop,2014,144,76,77,-5,31,93,225,4,4,79
215,216,Shake It Off,Taylor Swift,pop,2014,160,80,65,-5,33,94,219,6,17,78
216,217,Dark Horse,Katy Perry,dance pop,2014,132,59,65,-6,17,35,216,0,5,78
217,218,Hey Brother,Avicii,big room,2014,125,78,55,-5,8,46,255,3,4,78
218,219,Maps,Maroon 5,pop,2014,120,71,74,-6,6,88,190,2,3,78
219,220,Treasure,Bruno Mars,pop,2014,116,69,87,-5,32,94,179,4,4,77
220,221,Let Her Go,Passenger,folk-pop,2014,75,54,51,-7,10,24,253,39,6,77
221,222,Problem,Ariana Grande,dance pop,2014,103,81,66,-5,16,63,194,2,15,75
222,223,Pompeii,Bastille,metropopolis,2014,127,72,68,-6,27,57,214,8,4,73
223,224,Team,Lorde,art pop,2014,100,58,69,-7,31,42,193,17,9,73
224,225,Love Me Again,John Newman,pop,2014,126,89,50,-5,10,21,240,0,4,73
225,226,Latch,Disclosure,house,2014,122,73,50,-5,9,52,256,2,17,72
226,227,Adore You,Miley Cyrus,dance pop,2014,120,66,58,-5,11,20,279,11,3,72
227,228,Love Never Felt So Good,Michael Jackson,pop,2014,118,72,78,-6,7,71,246,13,4,71
228,229,Burn,Ellie Goulding,dance pop,2014,87,78,56,-5,11,33,231,31,4,71
229,230,She Looks So Perfect,5 Seconds of Summer,boy band,2014,160,95,49,-4,33,44,202,0,13,71
230,231,Fancy,Iggy Azalea,australian hip hop,2014,95,72,91,-4,5,38,200,9,7,70
231,232,Talk Dirty (feat. 2 Chainz),Jason Derulo,dance pop,2014,100,65,76,-7,31,76,178,3,23,68
232,233,Gorilla,Bruno Mars,pop,2014,140,54,72,-7,10,64,244,45,4,68
233,234,human,Christina Perri,dance pop,2014,144,49,44,-6,11,25,251,13,4,68
234,235,Young Girls,Bruno Mars,pop,2014,126,75,56,-5,21,50,229,46,3,67
235,236,Wiggle (feat. Snoop Dogg),Jason Derulo,dance pop,2014,82,62,70,-7,16,72,193,8,25,67
236,237,Love Runs Out,OneRepublic,dance pop,2014,120,93,72,-4,8,74,225,17,6,66
237,238,This Is How We Do,Katy Perry,dance pop,2014,96,64,69,-6,15,80,204,2,5,66
238,239,Mmm Yeah (feat. Pitbull),Austin Mahone,dance pop,2014,126,92,71,-4,27,98,232,0,4,65
239,240,A Little Party Never Killed Nobody (All We Got),Fergie,dance pop,2014,130,62,76,-6,9,52,241,1,18,65
240,241,#SELFIE,The Chainsmokers,electropop,2014,128,92,79,-3,8,66,184,1,25,65
241,242,Partition,Beyoncé,dance pop,2014,186,44,41,-12,31,17,319,3,29,65
242,243,Birthday,Katy Perry,dance pop,2014,126,67,72,-5,11,84,215,9,7,65
243,244,G.U.Y.,Lady Gaga,dance pop,2014,110,92,62,-3,12,57,233,1,4,65
244,245,Stay The Night - Featuring Hayley Williams Of ...,Zedd,complextro,2014,128,74,60,-3,9,46,217,11,4,64
245,246,"Let It Go - From ""Frozen / Single Version",Demi Lovato,dance pop,2014,140,66,50,-6,27,25,226,3,4,63
246,247,Wings,Birdy,neo mellow,2014,83,71,47,-5,16,22,252,8,3,62
247,248,Can't Remember to Forget You (feat. Rihanna),Shakira,colombian pop,2014,138,81,69,-4,14,82,207,12,7,62
248,249,Shot Me Down (feat. Skylar Grey) - Radio Edit,David Guetta,dance pop,2014,192,77,35,-4,12,4,191,6,5,61
249,250,Say Something,A Great Big World,neo mellow,2014,138,15,45,-9,9,9,229,87,3,61
250,251,A Sky Full of Stars,Coldplay,permanent wave,2014,125,68,55,-6,21,16,268,1,3,60
251,252,Come Get It Bae,Pharrell Williams,dance pop,2014,120,80,93,-6,10,90,202,27,8,59
252,253,Chandelier,Sia,australian dance,2014,174,78,29,-3,7,62,216,2,7,56
253,254,XO,Beyoncé,dance pop,2014,170,79,47,-9,31,21,216,17,26,56
254,255,We Are One (Ole Ola) [The Official 2014 FIFA W...,Pitbull,dance pop,2014,125,94,60,-4,10,55,222,0,7,56
255,256,Not About Angels,Birdy,neo mellow,2014,116,14,41,-10,9,23,190,97,4,56
256,257,Drunk in Love,Beyoncé,dance pop,2014,140,62,59,-7,18,40,323,1,5,52
257,258,Anaconda,Nicki Minaj,dance pop,2014,130,60,96,-6,21,65,260,7,18,50
258,259,Boom Clap - From the Motion Picture Das Schick...,Charli XCX,candy pop,2014,92,81,68,-4,34,64,169,7,6,50
259,260,La La La (Brasil 2014) (feat. Carlinhos Brown),Shakira,colombian pop,2014,128,82,80,-5,35,61,198,18,4,50
260,261,Tee Shirt - Soundtrack Version,Birdy,neo mellow,2014,76,34,68,-9,9,56,160,84,3,49
261,262,Words as Weapons,Birdy,neo mellow,2014,120,35,53,-9,14,19,239,28,3,44
262,263,You're Mine (Eternal),Mariah Carey,dance pop,2014,149,58,63,-7,38,56,224,28,7,38
263,264,Sheezus,Lily Allen,dance pop,2014,130,50,78,-7,11,39,235,15,4,37
264,265,Cannonball,Lea Michele,hollywood,2014,92,82,56,-3,19,57,215,2,5,37
265,266,It's On Again - Main Soundtrack,Alicia Keys,hip pop,2014,110,54,64,-9,25,53,230,10,11,30
266,267,I Luh Ya Papi,Jennifer Lopez,dance pop,2014,96,73,74,-6,12,59,207,45,42,28
267,268,Not a Bad Thing,Justin Timberlake,dance pop,2014,86,73,59,-6,38,46,266,27,6,0

# MERGIAR O DATASET
- O join  - O join combina os dataframes com base no index
- O merge - O Merge combina os dataframes quando você indica as colunas
- O appending - Quando você " cola " um dataframe embaixo do outro

In [ ]:
df.merge(dfs,left_on='artist',right_on='Artists',how='left').fillna(0)

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,...,spch,pop,Country,Continent,Rank,Title,Artists,Album,Explicit,Duration
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,...,4,83,0,0,0.0,0,0,0,0.0,0
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,...,23,82,0,0,0.0,0,0,0,0.0,0
2,3,TiK ToK,Kesha,dance pop,2010,120,84,76,-3,29,...,14,80,0,0,0.0,0,0,0,0.0,0
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,...,4,79,0,0,0.0,0,0,0,0.0,0
4,5,Just the Way You Are,Bruno Mars,pop,2010,109,84,64,-5,9,...,4,78,0,0,0.0,0,0,0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1858,599,Find U Again (feat. Camila Cabello),Mark Ronson,dance pop,2019,104,66,61,-7,20,...,3,75,0,0,0.0,0,0,0,0.0,0
1859,600,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,2019,95,79,75,-6,7,...,12,75,0,0,0.0,0,0,0,0.0,0
1860,601,"No Brainer (feat. Justin Bieber, Chance the Ra...",DJ Khaled,dance pop,2019,136,76,53,-5,9,...,34,70,0,0,0.0,0,0,0,0.0,0
1861,602,Nothing Breaks Like a Heart (feat. Miley Cyrus),Mark Ronson,dance pop,2019,114,79,60,-6,42,...,7,69,0,0,0.0,0,0,0,0.0,0
1862,603,Kills You Slowly,The Chainsmokers,electropop,2019,150,44,70,-9,13,...,6,67,0,0,0.0,0,0,0,0.0,0

In [ ]:
df.merge(dfs,left_on='artist',right_on='Artists',how='left', indicator=True).fillna(0)

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,...,pop,Country,Continent,Rank,Title,Artists,Album,Explicit,Duration,_merge
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,...,83,0,0,0.0,0,0,0,0.0,0,left_only
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,...,82,0,0,0.0,0,0,0,0.0,0,left_only
2,3,TiK ToK,Kesha,dance pop,2010,120,84,76,-3,29,...,80,0,0,0.0,0,0,0,0.0,0,left_only
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,...,79,0,0,0.0,0,0,0,0.0,0,left_only
4,5,Just the Way You Are,Bruno Mars,pop,2010,109,84,64,-5,9,...,78,0,0,0.0,0,0,0,0.0,0,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1858,599,Find U Again (feat. Camila Cabello),Mark Ronson,dance pop,2019,104,66,61,-7,20,...,75,0,0,0.0,0,0,0,0.0,0,left_only
1859,600,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,2019,95,79,75,-6,7,...,75,0,0,0.0,0,0,0,0.0,0,left_only
1860,601,"No Brainer (feat. Justin Bieber, Chance the Ra...",DJ Khaled,dance pop,2019,136,76,53,-5,9,...,70,0,0,0.0,0,0,0,0.0,0,left_only
1861,602,Nothing Breaks Like a Heart (feat. Miley Cyrus),Mark Ronson,dance pop,2019,114,79,60,-6,42,...,69,0,0,0.0,0,0,0,0.0,0,left_only
1862,603,Kills You Slowly,The Chainsmokers,electropop,2019,150,44,70,-9,13,...,67,0,0,0.0,0,0,0,0.0,0,left_only

In [ ]:
df.join(dfs)

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,...,spch,pop,Country,Continent,Rank,Title,Artists,Album,Explicit,Duration
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,...,4,83,Global,Global,1,Rain On Me (with Ariana Grande),"Lady Gaga, Ariana Grande",Rain On Me (with Ariana Grande),0,3:02
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,...,23,82,Global,Global,2,Blinding Lights,The Weeknd,After Hours,0,3:20
2,3,TiK ToK,Kesha,dance pop,2010,120,84,76,-3,29,...,14,80,Global,Global,3,ROCKSTAR (feat. Roddy Ricch),"DaBaby, Roddy Ricch",BLAME IT ON BABY,1,3:01
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,...,4,79,Global,Global,4,Roses - Imanbek Remix,"SAINt JHN, Imanbek",Roses (Imanbek Remix),1,2:56
4,5,Just the Way You Are,Bruno Mars,pop,2010,109,84,64,-5,9,...,4,78,Global,Global,5,Toosie Slide,Drake,Dark Lane Demo Tapes,1,4:07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
598,599,Find U Again (feat. Camila Cabello),Mark Ronson,dance pop,2019,104,66,61,-7,20,...,3,75,Costa Rica,North America,49,The Box,Roddy Ricch,Please Excuse Me For Being Antisocial,1,3:16
599,600,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,2019,95,79,75,-6,7,...,12,75,Costa Rica,North America,50,CANCIÓN CON YANDEL,"Yandel, Bad Bunny",LAS QUE NO IBAN A SALIR,1,3:29
600,601,"No Brainer (feat. Justin Bieber, Chance the Ra...",DJ Khaled,dance pop,2019,136,76,53,-5,9,...,34,70,Czech Republic,Europe,1,Blinding Lights,The Weeknd,After Hours,0,3:20
601,602,Nothing Breaks Like a Heart (feat. Miley Cyrus),Mark Ronson,dance pop,2019,114,79,60,-6,42,...,7,69,Czech Republic,Europe,2,Roses - Imanbek Remix,"SAINt JHN, Imanbek",Roses (Imanbek Remix),1,2:56
602,603,Kills You Slowly,The Chainsmokers,electropop,2019,150,44,70,-9,13,...,6,67,Czech Republic,Europe,3,GOOBA,6ix9ine,GOOBA,1,2:12

In [ ]:
df.append(dfs).fillna('hehe')

<ipython-input-69-f2f5816b5c08>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df.append(dfs).fillna('hehe')

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,...,spch,pop,Country,Continent,Rank,Title,Artists,Album,Explicit,Duration
0,1.0,"Hey, Soul Sister",Train,neo mellow,2010.0,97.0,89.0,67.0,-4.0,8.0,...,4.0,83.0,hehe,hehe,hehe,hehe,hehe,hehe,hehe,hehe
1,2.0,Love The Way You Lie,Eminem,detroit hip hop,2010.0,87.0,93.0,75.0,-5.0,52.0,...,23.0,82.0,hehe,hehe,hehe,hehe,hehe,hehe,hehe,hehe
2,3.0,TiK ToK,Kesha,dance pop,2010.0,120.0,84.0,76.0,-3.0,29.0,...,14.0,80.0,hehe,hehe,hehe,hehe,hehe,hehe,hehe,hehe
3,4.0,Bad Romance,Lady Gaga,dance pop,2010.0,119.0,92.0,70.0,-4.0,8.0,...,4.0,79.0,hehe,hehe,hehe,hehe,hehe,hehe,hehe,hehe
4,5.0,Just the Way You Are,Bruno Mars,pop,2010.0,109.0,84.0,64.0,-5.0,9.0,...,4.0,78.0,hehe,hehe,hehe,hehe,hehe,hehe,hehe,hehe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3145,hehe,hehe,hehe,hehe,hehe,hehe,hehe,hehe,hehe,hehe,...,hehe,hehe,Vietnam,Asia,46.0,ĐÃ TỪNG LÀ,Vũ.,ĐÃ TỪNG LÀ,0.0,4:20
3146,hehe,hehe,hehe,hehe,hehe,hehe,hehe,hehe,hehe,hehe,...,hehe,hehe,Vietnam,Asia,47.0,Mượn Rượu Tỏ Tình,"BigDaddy, Emily",Mượn Rượu Tỏ Tình,0.0,3:18
3147,hehe,hehe,hehe,hehe,hehe,hehe,hehe,hehe,hehe,hehe,...,hehe,hehe,Vietnam,Asia,48.0,Ngày Tận Thế,"Tóc Tiên, Da LAB, Touliver",Ngày Tận Thế,0.0,3:52
3148,hehe,hehe,hehe,hehe,hehe,hehe,hehe,hehe,hehe,hehe,...,hehe,hehe,Vietnam,Asia,49.0,Đi Đu Đưa Đi,Bich Phuong,Đi Đu Đưa Đi,0.0,3:40
3149,hehe,hehe,hehe,hehe,hehe,hehe,hehe,hehe,hehe,hehe,...,hehe,hehe,Vietnam,Asia,50.0,Blinding Lights,The Weeknd,After Hours,0.0,3:20

In [ ]:
df_grouped=df.groupby('artist')['title'].count()

In [ ]:
df_grouped=df_grouped.reset_index()

In [ ]:
df[:10].style.background_gradient(axis=0)

In [ ]:
df[:15].style.text_gradient(low=0.75,high=1.3)

###AGORA É HORA DE COMEÇAR O NUMPY ! :))))
---
Numpy é uma biblioteca do Python que trabalha e opera vetores/Arrays.
Arrays unidimensionais, bidimensionais e até mesmo tridimensionais ou com mais dimensões.
Muito mais rápido que os outros tipos de dados do python. até 10x mais rápido, facilidade para encontrar os dados, melhor alocação de memória *usa menos* !

In [ ]:
import numpy as np
#importando o Numpy

In [ ]:
vetor_linha=np.array([1,2,3,4,5])
#criando uma variável chamada vetor_linha e atribuindo alguns valores a ela

In [ ]:
print(vetor_linha)

[1 2 3 4 5]

In [ ]:
vetor_coluna=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
#Criando uma var chamada vetor_coluna e colocando dados dentro dela ( primeira matriz de vdd)

In [ ]:
print(vetor_coluna)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

In [ ]:
matriz = np.array([[14,62,3],[6,4,8],[12,65,78]])
#fiz a mesma coisa de cima

In [ ]:
print(matriz)

[[14 62  3]
 [ 6  4  8]
 [12 65 78]]

In [ ]:
np.linspace(0,20,num=5)
#linspace vai criar um vetor ( array) e vai preencher ele baseado nas coisas que você definiu

array([ 0.,  5., 10., 15., 20.])

In [ ]:
np.random.randint(0,11,3)
#Criando vetor randômico de 0 a 11, com três elementos

array([7, 0, 7])

In [ ]:
print(matriz.shape)
#mostrando o shape da matriz

(3, 3)

In [ ]:
print(matriz.dtype)
#Tipo de dados da matriz

int64

In [ ]:
print(matriz.size)
#quantidade de elementos dentro da matriz

9

In [ ]:
print(matriz.ndim)
#Número de dimensões

2

In [ ]:
print(np.min(matriz))
#menor número dentro da matriz

3

In [ ]:
print(np.max(matriz))
#Maior número dentro da matriz

78

In [ ]:
print(np.max(matriz,axis=0))
#exibir maiores números de cada uma das colunas

[14 65 78]

In [ ]:
print(np.min(matriz,axis=1))
#menor valor de cad auma das colunas

[ 3  4 12]

In [ ]:
a = np.arange(6)

In [ ]:
print(a)

[0 1 2 3 4 5]

In [ ]:
#Reshape as - Mudança de formato - De array to matriz
b = a.reshape(3,2)

In [ ]:
print(b)

[[0 1]
 [2 3]
 [4 5]]

In [ ]:
#basic array creation
s=np.array([1,9,15,4])

In [ ]:
print(s)

[ 1  9 15  4]

In [ ]:
np.sort(s)

array([ 1,  4,  9, 15])

In [ ]:
print(a)

[0 1 2 3 4 5]

In [ ]:
print(s)

[ 1  9 15  4]

In [ ]:
#concatenate
t = np.concatenate((a,s))

In [ ]:
#Sort/organize  - nesse caso aqui, em função da ordem crescente
np.sort(t)

array([ 0,  1,  1,  2,  3,  4,  4,  5,  9, 15])

# Operações matemáticas

In [ ]:
#Desvio padrão ( em função da matriz)
np.std(matriz)

28.986586936412884

In [ ]:
#pERCENTIL EM FUNÇÃO DE 10
np.percentile(a,10)

0.5

In [ ]:
#variança
np.var(matriz)

840.2222222222222

In [ ]:
#matriz transposta
matriz.T

array([[14,  6, 12],
       [62,  4, 65],
       [ 3,  8, 78]])

In [ ]:
print(matriz)

[[14 62  3]
 [ 6  4  8]
 [12 65 78]]

#Operações com Matrizes

In [ ]:
matriz1= np.array([[14,2,3],[48,6,8]])

In [ ]:
matriz2=np.array([[1,21,3],[4,54,66]])

In [ ]:
print(matriz1)

[[14  2  3]
 [48  6  8]]

In [ ]:
print(matriz2)

[[ 1 21  3]
 [ 4 54 66]]

In [ ]:
#Soma de matrizes
print(np.add(matriz1,matriz2))

[[15 23  6]
 [52 60 74]]

In [ ]:
#Subtração de matrizes

print(np.subtract(matriz1,matriz2))

[[ 13 -19   0]
 [ 44 -48 -58]]

In [ ]:
#Multiplicação
print(np.multiply(matriz1,matriz2))
#ou eu posso usar apenas operadores aritiméticos simples

[[ 14  42   9]
 [192 324 528]]

In [ ]:
#Calculos diagonais -

In [ ]:
#Diagonal principal
print(matriz1.diagonal())

[14  6]

In [ ]:
print(matriz1.diagonal(offset=1))

[2 8]

In [ ]:
print(matriz1.diagonal(offset=-1))

[48]

##MATRIZ INVERSA

In [ ]:
print(matriz)

[[14 62  3]
 [ 6  4  8]
 [12 65 78]]

In [ ]:
#matriz inversa
print(np.linalg.inv(matriz))

[[ 0.00833667  0.18601202 -0.0193988 ]
 [ 0.01490982 -0.04232465  0.00376754]
 [-0.01370741  0.00665331  0.01266533]]

#Adição e remoção de elementos ao Array/matriz

In [ ]:
#Criar uma função
add_100=lambda i:i+100

In [ ]:
# Criar o objeto de adição ( para fazer a função funcionar ) _add_100=np.vectorize(add_100)

In [ ]:
#Código inútil xD ---

print(_add_100)

<numpy.vectorize object at 0x7f026569bc70>

In [ ]:
#Printar o objeto sendo adicionado a matriz !
print(_add_100(matriz))

[[114 162 103]
 [106 104 108]
 [112 165 178]]

#Operações lógicas com arrays

In [ ]:
print(a)

[0 1 2 3 4 5]

In [ ]:

print(np.where(a<4))

(array([0, 1, 2, 3]),)

In [ ]:
print(np.where(a>2))

(array([3, 4, 5]),)

In [ ]:
print(np.where(a!=2))

(array([0, 1, 3, 4, 5]),)

In [ ]:
print(np.where(a==3))

(array([3]),)

In [ ]:
print(np.where((a>2)&(a!=3)))

(array([4, 5]),)

In [ ]:
print(np.where((a>2)|(a!=3)))

(array([0, 1, 2, 3, 4, 5]),)